/* this code was generated by automated tool, 
   should not edit by hand */

export interface User {
  GetUser(request: UserRequest): Promise<UserReply>;
}

export interface UserRequest {
  name?: string;
}

export interface UserReply {
  name?: string;
}
